version: "3.7"
services:
  landing:
    container_name: lens_federated-search
    image: ghcr.io/samply/cce-explorer:pr-1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`${GUI_HOST}`)"
      - "traefik.http.routers.landing.tls=true"

  spot:
    image: samply/rustyspot:latest
    platform: linux/amd64
    environment:
      HTTP_PROXY: ${http_proxy}
      HTTPS_PROXY: ${https_proxy}
      NO_PROXY: beam-proxy, prism
      BEAM_SECRET: "${LOCAL_BEAM_SECRET_SPOT}"
      BEAM_PROXY_URL: http://beam-proxy:8081
      BEAM_APP_ID: "spot.${LOCAL_BEAM_ID}.${BROKER_HOST}"
      CORS_ORIGIN: "https://${GUI_HOST}"
      SITES: ${SITES}
      TRANSFORM: LENS
      PROJECT: cce
      BIND_ADDR: 0.0.0.0:8055
      PRISM_URL: http://prism:8066
      RUST_LOG: "info"
      LOG_FILE: /logs/requests.log
    volumes:
      - ./logs:/logs
    depends_on:
      - "beam-proxy"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.spot.loadbalancer.server.port=8055"
      - "traefik.http.middlewares.corsheaders2.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.corsheaders2.headers.accesscontrolallowheaders=content-type"
      - "traefik.http.middlewares.corsheaders2.headers.accesscontrolalloworiginlist=https://${HOST}"
      - "traefik.http.middlewares.corsheaders2.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.corsheaders2.headers.accesscontrolmaxage=-1"
      - "traefik.http.routers.spot.rule=Host(`${HOST}`) && PathPrefix(`/prod`)"
      - "traefik.http.middlewares.stripprefix_spot.stripprefix.prefixes=/prod"
      - "traefik.http.routers.spot.tls=true"
      - "traefik.http.routers.spot.middlewares=corsheaders2,stripprefix_spot,auth"
a