version: "3.7"

services:

  teiler-orchestrator:
    image: docker.verbis.dkfz.de/cache/samply/teiler-orchestrator:latest
    container_name: bridgehead-teiler-orchestrator
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teiler_orchestrator_kr.rule=PathPrefix(`/kr-teiler`)"
      - "traefik.http.services.teiler_orchestrator_kr.loadbalancer.server.port=9000"
      - "traefik.http.routers.teiler_orchestrator_kr.tls=true"
      - "traefik.http.middlewares.teiler_orchestrator_kr_strip.stripprefix.prefixes=/kr-teiler"
      - "traefik.http.routers.teiler_orchestrator_kr.middlewares=teiler_orchestrator_kr_strip"
    environment:
      TEILER_BACKEND_URL: "/kr-teiler-backend"
      TEILER_DASHBOARD_URL: "/kr-teiler-dashboard"
      DEFAULT_LANGUAGE: "${TEILER_DEFAULT_LANGUAGE_LOWER_CASE}"
      HTTP_RELATIVE_PATH: "/kr-teiler"

  teiler-dashboard:
    image: docker.verbis.dkfz.de/cache/samply/teiler-dashboard:${TEILER_DASHBOARD_TAG}
    container_name: bridgehead-teiler-dashboard
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teiler_dashboard_kr.rule=PathPrefix(`/kr-teiler-dashboard`)"
      - "traefik.http.services.teiler_dashboard_kr.loadbalancer.server.port=80"
      - "traefik.http.routers.teiler_dashboard_kr.tls=true"
      - "traefik.http.middlewares.teiler_dashboard_kr_strip.stripprefix.prefixes=/kr-teiler-dashboard"
      - "traefik.http.routers.teiler_dashboard_kr.middlewares=teiler_dashboard_kr_strip"
    environment:
      DEFAULT_LANGUAGE: "${TEILER_DEFAULT_LANGUAGE}"
      TEILER_BACKEND_URL: "/kr-teiler-backend"
      TEILER_DASHBOARD_URL: "/kr-teiler-dashboard"
      TEILER_ADMIN_NAME: "${OPERATOR_FIRST_NAME} ${OPERATOR_LAST_NAME}"
      TEILER_ADMIN_EMAIL: "${OPERATOR_EMAIL}"
      TEILER_ADMIN_PHONE: "${OPERATOR_PHONE}"
      TEILER_PROJECT: "${PROJECT}"
      EXPORTER_API_KEY: "${EXPORTER_API_KEY}"
      TEILER_ORCHESTRATOR_URL: "/kr-teiler"
      TEILER_ORCHESTRATOR_HTTP_RELATIVE_PATH: "/kr-teiler"
      REPORTER_DEFAULT_TEMPLATE_ID: "ccp-qb"
      EXPORTER_DEFAULT_TEMPLATE_ID: "ccp"


  teiler-backend:
    image: docker.verbis.dkfz.de/ccp/kr-teiler-backend:latest
    container_name: bridgehead-teiler-backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teiler_backend_kr.rule=PathPrefix(`/kr-teiler-backend`)"
      - "traefik.http.services.teiler_backend_kr.loadbalancer.server.port=8085"
      - "traefik.http.routers.teiler_backend_kr.tls=true"
      - "traefik.http.middlewares.teiler_backend_kr_strip.stripprefix.prefixes=/kr-teiler-backend"
      - "traefik.http.routers.teiler_backend_kr.middlewares=teiler_backend_kr_strip"
    environment:
      LOG_LEVEL: "INFO"
      APPLICATION_PORT: "8085"
      DEFAULT_LANGUAGE: "${TEILER_DEFAULT_LANGUAGE}"
      TEILER_ORCHESTRATOR_HTTP_RELATIVE_PATH: "/kr-teiler"
      TEILER_ORCHESTRATOR_URL: "/kr-teiler"
      TEILER_DASHBOARD_DE_URL: "/kr-teiler-dashboard/de"
      TEILER_DASHBOARD_EN_URL: "/kr-teiler-dashboard/en"
      HTTP_PROXY: "http://forward_proxy:3128"
