version: "3.7"

services:
  traefik:
    container_name: bridgehead-traefik
    image: traefik:latest
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker=true
      - --api.dashboard=true
      - --accesslog=true # print access-logs
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
    labels:
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${bc_auth_users}"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../certs:/tools/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  forward_proxy:
    container_name: bridgehead-forward-proxy
    image: samply/bridgehead-forward-proxy:develop
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    volumes:
      - "bridgehead-proxy:/var/log/squid"
    
  landing:
    container_name: bridgehead-landingpage
    image: samply/bridgehead-landingpage:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=PathPrefix(`/`)"
      - "traefik.http.services.landing.loadbalancer.server.port=80"
      - "traefik.http.routers.landing.tls=true"
    environment:
      HOST: ${HOST}
      PROJECT: ${PROJECT}
      SITE_NAME: ${SITE_NAME}
      
  idmanager:
    image: docker.verbis.dkfz.de/ccp/idmanager:bk2
    ports:
      - "8084:8080"
    restart: always

  store:
    image: docker.verbis.dkfz.de/ccp/samply.store:bk2
    ports:
      - "8083:8080"
      - "65495:65395"
    environment:
      HTTP_PROXY_HOST: ${HTTP_PROXY_URL}
      HTTPS_PROXY_HOST: ${HTTPS_PROXY_URL}
    volumes:
      - "store_logs:/usr/local/tomcat/logs"
    restart: always

  connector:
    image: docker.verbis.dkfz.de/ccp/connector:bk2
    ports:
    - "8082:8080"
    - "65496:65395"
    environment:
      POSTGRES_PASSWORD: ${CONNECTOR_POSTGRES_PASSWORD}
      NNGM_MAGICPL_APIKEY: ${NNGM_MAGICPL_APIKEY}
      NNGM_MAINZELLISTE_APIKEY: ${NNGM_MAINZELLISTE_APIKEY}
      NNGM_CTS_APIKEY: ${NNGM_CTS_APIKEY}
      NNGM_CRYPTKEY: ${NNGM_CRYPTKEY}
      HTTP_PROXY_HOST: ${HTTP_PROXY_URL}
      HTTPS_PROXY_HOST: ${HTTPS_PROXY_URL}
    volumes:
      - "connector_logs:/usr/local/tomcat/logs"
    restart: always

  ## Databases
  store_db:
    image: postgres:9.5-alpine
    command: postgres -c datestyle='iso, dmy'
    environment:
      POSTGRES_DB: ${STORE_POSTGRES_DB}
      POSTGRES_USER: ${STORE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STORE_POSTGRES_PASSWORD}
    volumes:
      - "store_db_data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5450:5432"

  connector_db:
    image: postgres:9.5-alpine
    container_name: bridgehead-ccp-connector-db
    volumes:
      - "connector_db_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: "samplyconnector"
      POSTGRES_USER: "samplyconnector"
      POSTGRES_PASSWORD: ${CONNECTOR_POSTGRES_PASSWORD}
    restart: always

volumes:
  blaze-data:
  bridgehead-proxy:
  connector_db_data:
    name: bridgehead_connector_db_data
  store_db_data:
    name: bridgehead_store_db_data
  connector_logs:  
  store_logs:
