version: "3.7"

services:
  ssh-tunnel:
    image: docker.verbis.dkfz.de/cache/samply/ssh-tunnel
    container_name: bridgehead-ccp-ssh-tunnel
    environment:
      SSH_TUNNEL_USERNAME: "${SSH_TUNNEL_USERNAME}"
      SSH_TUNNEL_HOST: "${SSH_TUNNEL_HOST}"
      SSH_TUNNEL_PORT: "${SSH_TUNNEL_PORT:-22}"
    volumes:
      - "/etc/bridgehead/ssh-tunnel.conf:/ssh-tunnel.conf:ro"
      - "/etc/bridgehead/pki/ssh-tunnel.priv.pem:/run/secrets/privkey:ro"
