#!/bin/bash -e

baseDir() {
	# see https://stackoverflow.com/questions/59895
	SOURCE=${BASH_SOURCE[0]}
	while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
		DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
		SOURCE=$(readlink "$SOURCE")
		[[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
	done
	DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
	echo $DIR
}

BASE=$(baseDir)
cd $BASE

source ./lib/functions.sh

ACTION=$1
export PROJECT=$2

if [[ -z $1 || -z $2 ]]; then
	printUsage
	exit 1
fi

case "$PROJECT" in
	ccp)
		#nothing extra to do
		;;
	nngm)
		#nothing extra to do
		;;
	gbn)
		#nothing extra to do
		;;
	*)
		printUsage
		exit 1
		;;
esac

# Load variables from /etc/bridgehead and /srv/docker/bridgehead
set -a
source /etc/bridgehead/$PROJECT.conf || fail_and_report 1 "/etc/bridgehead/$PROJECT.conf not found"
fetchVarsFromVaultByFile /etc/bridgehead/$PROJECT.conf || fail_and_report 1 "Unable to fetchVarsFromVaultByFile"
[ -e ./$PROJECT/vars ] && source ./$PROJECT/vars
set +a

OVERRIDE=""
if [ -f "$PROJECT/docker-compose.override.yml" ]; then
	log INFO "Apply docker-compose.override.yml"
	OVERRIDE+="-f ./$PROJECT/docker-compose.override.yml"
fi

case "$ACTION" in
	start)
		hc_send log "Bridgehead $PROJECT startup: Checking requirements ..."
		checkRequirements
		hc_send log "Bridgehead $PROJECT startup: Requirements checked out. Now starting bridgehead ..."
		exec docker-compose -f ./$PROJECT/docker-compose.yml $OVERRIDE up --abort-on-container-exit
		;;
	stop)
		exec docker-compose -f ./$PROJECT/docker-compose.yml $OVERRIDE down
		;;
	update)
		exec ./lib/update-bridgehead.sh $PROJECT
		;;
	install)
		exec ./lib/setup-bridgehead-units.sh $PROJECT
		;;
	uninstall)
		exec ./lib/remove-bridgehead-units.sh $PROJECT
		;;
	preRun | preUpdate)
		fixPermissions
		;;
	postRun | postUpdate)
		;;
	*)
		printUsage
		exit 1
		;;
esac

exit 0
