version: "3.7"

services:
  directory_sync_service:
    image: "docker.verbis.dkfz.de/cache/samply/directory_sync_service"
    environment:
      DS_DIRECTORY_URL: ${DS_DIRECTORY_URL}
      DS_DIRECTORY_USER_NAME: ${DS_DIRECTORY_USER_NAME}
      DS_DIRECTORY_PASS_CODE: ${DS_DIRECTORY_PASS_CODE}
      DS_TIMER_CRON: ${DS_TIMER_CRON}
