version: "3.7"

services:
  focus-eric:
    image: docker.verbis.dkfz.de/cache/samply/focus:${FOCUS_TAG}
    container_name: bridgehead-focus-eric
    environment:
      API_KEY: ${ERIC_FOCUS_BEAM_SECRET_SHORT}
      BEAM_APP_ID_LONG: focus.${ERIC_PROXY_ID}
      PROXY_ID: ${ERIC_PROXY_ID}
      BLAZE_URL: "http://blaze:8080/fhir/"
      BEAM_PROXY_URL: http://beam-proxy-eric:8081
      RETRY_COUNT: ${FOCUS_RETRY_COUNT}
    depends_on:
      - "beam-proxy-eric"
      - "blaze"

  beam-proxy-eric:
    image: docker.verbis.dkfz.de/cache/samply/beam-proxy:develop
    container_name: bridgehead-beam-proxy-eric
    environment:
      BROKER_URL: ${ERIC_BROKER_URL}
      PROXY_ID: ${ERIC_PROXY_ID}
      APP_focus_KEY: ${ERIC_FOCUS_BEAM_SECRET_SHORT}
      APP_feedback-agent_KEY: App1Secret
      PRIVKEY_FILE: /run/secrets/proxy.pem
      ALL_PROXY: http://forward_proxy:3128
      TLS_CA_CERTIFICATES_DIR: /conf/trusted-ca-certs
      ROOTCERT_FILE: /conf/root.crt.pem
    secrets:
      - proxy.pem
    depends_on:
      - "forward_proxy"
    volumes:
      - /etc/bridgehead/trusted-ca-certs:/conf/trusted-ca-certs:ro
      - /srv/docker/bridgehead/bbmri/modules/${ERIC_ROOT_CERT}.root.crt.pem:/conf/root.crt.pem:ro

