version: "3.7"

services:
  exporter:
    labels:
      # Main router
      - "traefik.http.routers.exporter_${PLATFORM}.priority=20"

      # API router
      - "traefik.http.routers.exporter_${PLATFORM}_api.middlewares=exporter_${PLATFORM}_strip,exporter_auth"
      - "traefik.http.routers.exporter_${PLATFORM}_api.rule=PathRegexp(`/${PLATFORM}-exporter/.+`)"
      - "traefik.http.routers.exporter_${PLATFORM}_api.tls=true"
      - "traefik.http.routers.exporter_${PLATFORM}_api.priority=25"

      # Shared middlewares
      - "traefik.http.middlewares.exporter_auth.basicauth.users=${EXPORTER_USER}"

  reporter:
    labels:
      - "traefik.http.routers.reporter_${PLATFORM}.priority=20"

      #- "traefik.http.routers.reporter_${PLATFORM}.middlewares=reporter_${PLATFORM}_strip,exporter_auth"
      - "traefik.http.routers.reporter_${PLATFORM}_api.middlewares=reporter_${PLATFORM}_strip,exporter_auth"
      - "traefik.http.routers.reporter_${PLATFORM}_api.rule=PathRegexp(`/${PLATFORM}-reporter/.+`)"
      - "traefik.http.routers.reporter_${PLATFORM}_api.tls=true"
      - "traefik.http.routers.reporter_${PLATFORM}_api.priority=25"
      #- "traefik.http.middlewares.reporter_auth.basicauth.users=${EXPORTER_USER}"



