version: "3.7"

services:
  exliquid-task-store:
    image: "samply/blaze:0.18"
    container_name: bridgehead-exliquid-task-store
    environment:
      BASE_URL: "http://bridgehead-exliquid-task-store:8080"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
    volumes:
    - "exliquid-task-store-data:/app/data"
    labels:
      - "traefik.enable=false"

  exliquid-report-hub:
    image: "samply/report-hub:latest"
    container_name: bridgehead-exliquid-report-hub
    environment:
      SPRING_WEBFLUX_BASE_PATH: "/exliquid"
      JAVA_TOOL_OPTIONS: "-Xmx1g"
      APP_BEAM_APPID: "report-hub.${PROXY_ID}"
      APP_BEAM_SECRET: ${REPORTHUB_BEAM_SECRET_SHORT}
      APP_BEAM_PROXY_BASEURL: http://beam-proxy:8081
      APP_TASKSTORE_BASEURL: "http://bridgehead-exliquid-task-store:8080/fhir"
      APP_DATASTORE_BASEURL:  http://bridgehead-ccp-blaze:8080/fhir
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.report-ccp.rule=PathPrefix(`/exliquid`)"
      - "traefik.http.services.report-ccp.loadbalancer.server.port=8080"
      - "traefik.http.routers.report-ccp.tls=true"

volumes:
  exliquid-task-store-data: