services:
  omics-endpoint:
    image: ghcr.io/samply/itcc-omics-ingest:data-lake-s3
    environment:
      API_KEY: ${GENERATE_API_KEY}
      RUST_LOG: debug
      BEAM_ID: "omics-endpoint.${PROXY_ID}"
      BEAM_SECRET: "${FOCUS_BEAM_SECRET_SHORT}"
      BEAM_URL: http://beam-proxy:8081
      ML_URL: http://mainzelliste:8080
      BLAZE_URL: http://bridgehead-itcc-blaze:8080/fhir/
      DATA_LAKE_ID: "${DATA_LAKE_ID}"
      PARTNER_ID: itcc-inform
      ML_API_KEY: ${GENERATE_API_KEY}

    volumes:
      - /var/cache/bridgehead/omics/data:/data/uploads
    labels:
      - "traefik.http.routers.omics.rule=Host(`${HOST}`) && PathPrefix(`/api/omics`)"
      - "traefik.enable=true"
      - "traefik.http.services.omics.loadbalancer.server.port=6080"
      - "traefik.http.routers.omics.tls=true"
      - "traefik.http.middlewares.omics-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.omics.middlewares=omics-stripprefix"

  db:
    image: postgres:15
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: mainzelliste
      POSTGRES_USER: ${ML_DB_USER}
      POSTGRES_PASSWORD: ${PATIENTLIST_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  mainzelliste:
    image: medicalinformatics/mainzelliste:latest
    container_name: mainzelliste
    restart: unless-stopped
    depends_on:
      - db

    ports:
      - 7887:8080

    environment:
      ML_API_KEY: ${GENERATE_API_KEY}
      ML_DB_HOST: db
      ML_DB_PORT: "5432"
      ML_DB_NAME: mainzelliste
      ML_DB_USER: ${ML_DB_USER}
      ML_DB_PASS: ${PATIENTLIST_POSTGRES_PASSWORD}
      ML_LOG_LEVEL: INFO
    volumes:
      - /etc/bridgehead/mainzelliste/mainzelliste.conf:/etc/mainzelliste/mainzelliste.conf
      - /etc/bridgehead/mainzelliste/keyset_siv.json:/etc/resources/keys/symmetric_key.der

volumes:
  db_data:
