services:
  omics-endpoint:
    build: .
    image: ghcr.io/samply/itcc-omics-ingest:workflow
    ports:
      - "6080:6080"
    environment:
      - UPLOAD_DIR=/data/uploads
      - RUST_LOG=trace
    volumes:
      - ./uploads:/data/uploads
    labels:
      - "traefik.http.routers.omics.rule=Host(`${HOST}`) && PathPrefix(`/api`)"
      - "traefik.enable=true"
      - "traefik.http.services.omics.loadbalancer.server.port=6080"
      - "traefik.http.routers.omics.tls=true"
